### PR TITLE
Fix GitHub actions issues

### PR DESCRIPTION
**Pull request by hugodahl**
Fixing action issues from Infrastructure issues list for GitHub action failures

### CODE REVIEW

**Comment by evaherrada** [comment]
@tannewt If I remember correctly this is an issue with the python version in build.yml. Do you happen to remember which version is the right one to use (I'll make sure to make a note of it somewhere so I don't forget)

**Comment by dhalbert** [comment]
> @tannewt If I remember correctly this is an issue with the python version in build.yml. Do you happen to remember which version is the right one to use (I'll make sure to make a note of it somewhere so I don't forget)

You need at least 3.7

**Comment by evaherrada** [comment]
Cool. That's what I suspected it was. Thanks!

**Comment by evaherrada** [comment]
Not really sure about the current failure

**Comment by dhalbert** [comment]
> Not really sure about the current failure

This is `bleak` trying to use `bluetoothctl` without checking for it not being there. I'll check on this.

**Comment by dhalbert** [comment]
Uncomment and change this line to this new version in `docs/conf.py`:
```py
autodoc_mock_imports = ["bleak", "digitalio", "busio"]
```

**Comment by evaherrada** [comment]
Will do. Thanks!

**Pull request merged**
